#!/bin/bash
# Shared runtime configuration/env/template helpers for deploy scripts.

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "Error: scripts/deploy/lib/runtime_config.sh must be sourced, not executed directly." >&2
    exit 1
fi

SHARED_NGINX_TEMPLATE="${PROJECT_ROOT}/scripts/templates/nginx-default.conf.template"

build_postgres_multiple_databases() {
    echo "${SMD_DB_NAME}:${SMD_DB_USER}:${SMD_DB_PASSWORD},${BSS_DB_NAME}:${BSS_DB_USER}:${BSS_DB_PASSWORD},${KEA_DB_NAME}:${KEA_DB_USER}:${KEA_DB_PASSWORD},${PCS_DB_NAME}:${PCS_DB_USER}:${PCS_DB_PASSWORD},${STORK_DB_NAME}:${STORK_DB_USER}:${STORK_DB_PASSWORD}"
}

export_runtime_template_vars() {
    export HOST_IP PXE_INTERFACE PXE_CIDR DHCP_START DHCP_END DHCP_NETMASK
    export HTTP_PORT SMD_PORT BSS_PORT POSTGRES_PORT CLOUD_INIT_PORT PCS_PORT STORK_PORT STORK_AGENT_PORT
    export POSTGRES_USER POSTGRES_PASSWORD
    export SMD_DB_NAME SMD_DB_USER SMD_DB_PASSWORD
    export BSS_DB_NAME BSS_DB_USER BSS_DB_PASSWORD
    export KEA_DB_NAME KEA_DB_USER KEA_DB_PASSWORD
    export PCS_DB_NAME PCS_DB_USER PCS_DB_PASSWORD
    export STORK_DB_NAME STORK_DB_USER STORK_DB_PASSWORD
    export HYDRA_DB_PASSWORD
}

runtime_template_vars() {
    echo '${HOST_IP} ${PXE_INTERFACE} ${PXE_CIDR} ${DHCP_START} ${DHCP_END} ${DHCP_NETMASK} ${HTTP_PORT} ${SMD_PORT} ${BSS_PORT} ${POSTGRES_PORT} ${CLOUD_INIT_PORT} ${PCS_PORT} ${STORK_PORT} ${STORK_AGENT_PORT} ${KEA_DB_NAME} ${KEA_DB_USER} ${KEA_DB_PASSWORD} ${STORK_DB_NAME} ${STORK_DB_USER} ${STORK_DB_PASSWORD} ${PCS_DB_NAME} ${PCS_DB_USER} ${PCS_DB_PASSWORD}'
}

runtime_kea_template_vars() {
    echo '${PXE_INTERFACE} ${KEA_DB_NAME} ${KEA_DB_USER} ${KEA_DB_PASSWORD} ${POSTGRES_PORT} ${HOST_IP} ${HTTP_PORT} ${DHCP_START} ${DHCP_END} ${PXE_CIDR}'
}

runtime_nginx_template_vars() {
    echo '${HTTP_PORT} ${SMD_PORT} ${BSS_PORT} ${CLOUD_INIT_PORT} ${PCS_PORT} ${STORK_PORT}'
}

runtime_boot_template_vars() {
    echo '${HOST_IP} ${HTTP_PORT}'
}

render_template_file() {
    local template_path="$1"
    local output_path="$2"
    local vars="${3:-$(runtime_template_vars)}"
    local write_mode="${4:-local}"
    local announce="${5:-true}"

    [ -f "$template_path" ] || return 0

    if [ "$write_mode" = "sudo" ]; then
        envsubst "$vars" < "$template_path" | sudo tee "$output_path" > /dev/null
    else
        envsubst "$vars" < "$template_path" > "$output_path"
    fi

    if [ "$announce" = "true" ]; then
        echo "Generated $(basename "$output_path")"
    fi
}

render_templates_in_dir() {
    local source_dir="$1"
    local output_dir="$2"
    local vars="${3:-$(runtime_template_vars)}"
    local write_mode="${4:-local}"
    local skip_name="${5:-}"
    local template_path

    for template_path in "$source_dir"/*.template; do
        [ -f "$template_path" ] || continue

        local base
        base="$(basename "$template_path" .template)"
        if [ -n "$skip_name" ] && [ "$base" = "$skip_name" ]; then
            continue
        fi

        echo "  Processing $base..."
        render_template_file "$template_path" "$output_dir/$base" "$vars" "$write_mode" "false"
    done
}

copy_static_config_files() {
    local source_dir="$1"
    local output_dir="$2"
    local write_mode="${3:-local}"
    local static_file

    for static_file in "$source_dir"/*.sh "$source_dir"/*.py "$source_dir"/*.conf "$source_dir"/*.html "$source_dir"/user-data "$source_dir"/meta-data; do
        [ -f "$static_file" ] || continue

        local base
        base="$(basename "$static_file")"
        if [[ "$base" == *.template ]]; then
            continue
        fi

        echo "  Copying $base..."
        if [ "$write_mode" = "sudo" ]; then
            sudo cp "$static_file" "$output_dir/$base"
        else
            cp "$static_file" "$output_dir/$base"
        fi
    done
}

generate_quadlets_env_file() {
    local output_path="$1"
    local postgres_multiple_databases
    postgres_multiple_databases="$(build_postgres_multiple_databases)"

    sudo tee "$output_path" > /dev/null <<EOF
# OpenCHAMI Environment Configuration (auto-generated by deploy script)

# Network
HOST_IP=${HOST_IP}
PXE_INTERFACE=${PXE_INTERFACE}
PXE_CIDR=${PXE_CIDR}
DHCP_START=${DHCP_START}
DHCP_END=${DHCP_END}
DHCP_NETMASK=${DHCP_NETMASK}

# Service ports
HTTP_PORT=${HTTP_PORT}
SMD_PORT=${SMD_PORT}
BSS_PORT=${BSS_PORT}
POSTGRES_PORT=${POSTGRES_PORT}
CLOUD_INIT_PORT=${CLOUD_INIT_PORT}
PCS_PORT=${PCS_PORT}
STORK_PORT=${STORK_PORT}
STORK_AGENT_PORT=${STORK_AGENT_PORT}

# PostgreSQL
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_MULTIPLE_DATABASES=${postgres_multiple_databases}

# SMD Database
SMD_DBPORT=${POSTGRES_PORT}
SMD_DBNAME=${SMD_DB_NAME}
SMD_DBUSER=${SMD_DB_USER}
SMD_DBPASS=${SMD_DB_PASSWORD}
SMD_DBOPTS=sslmode=disable

# BSS Database
BSS_DBPORT=${POSTGRES_PORT}
BSS_DBNAME=${BSS_DB_NAME}
BSS_DBUSER=${BSS_DB_USER}
BSS_DBPASS=${BSS_DB_PASSWORD}
BSS_DBOPTS=sslmode=disable
HSM_URL=http://localhost:${HTTP_PORT}
BSS_IPXE_SERVER=${HOST_IP}
BSS_ADVERTISE_ADDRESS=${HOST_IP}
NFD_URL=http://${HOST_IP}:${HTTP_PORT}/hmi/v1/subscribe
SMS_SERVER=http://localhost:${HTTP_PORT}

# Kea Database
KEA_DB_NAME=${KEA_DB_NAME}
KEA_DB_USER=${KEA_DB_USER}
KEA_DB_PASSWORD=${KEA_DB_PASSWORD}

# PCS Database
PCS_DB_NAME=${PCS_DB_NAME}
PCS_DB_USER=${PCS_DB_USER}
PCS_DB_PASSWORD=${PCS_DB_PASSWORD}

# Stork
STORK_DB_NAME=${STORK_DB_NAME}
STORK_DB_USER=${STORK_DB_USER}
STORK_DB_PASSWORD=${STORK_DB_PASSWORD}
STORK_AGENT_SERVER_URL=http://localhost:${HTTP_PORT}
STORK_AGENT_HOST=${HOST_IP}
STORK_AGENT_PORT=${STORK_AGENT_PORT}

# Kea sidecar
DB_NAME=${KEA_DB_NAME}
DB_USER=${KEA_DB_USER}
DB_PASS=${KEA_DB_PASSWORD}
DB_PORT=${POSTGRES_PORT}
EOF
}

generate_docker_compose_env_file() {
    local output_path="$1"

    cat > "$output_path" <<EOF
# Generated by deploy/docker-compose.sh — do not edit manually
HOST_IP=$HOST_IP
PXE_INTERFACE=$PXE_INTERFACE
DHCP_START=$DHCP_START
DHCP_END=$DHCP_END
DHCP_NETMASK=$DHCP_NETMASK
PXE_CIDR=$PXE_CIDR
HTTP_PORT=$HTTP_PORT
SMD_PORT=$SMD_PORT
BSS_PORT=$BSS_PORT
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
SMD_DB_NAME=$SMD_DB_NAME
SMD_DB_USER=$SMD_DB_USER
SMD_DB_PASSWORD=$SMD_DB_PASSWORD
BSS_DB_NAME=$BSS_DB_NAME
BSS_DB_USER=$BSS_DB_USER
BSS_DB_PASSWORD=$BSS_DB_PASSWORD
KEA_DB_NAME=$KEA_DB_NAME
KEA_DB_USER=$KEA_DB_USER
KEA_DB_PASSWORD=$KEA_DB_PASSWORD
HYDRA_DB_PASSWORD=$HYDRA_DB_PASSWORD
CLOUD_INIT_PORT=$CLOUD_INIT_PORT
PCS_DB_NAME=$PCS_DB_NAME
PCS_DB_USER=$PCS_DB_USER
PCS_DB_PASSWORD=$PCS_DB_PASSWORD
PCS_PORT=$PCS_PORT
STORK_DB_NAME=$STORK_DB_NAME
STORK_DB_USER=$STORK_DB_USER
STORK_DB_PASSWORD=$STORK_DB_PASSWORD
STORK_PORT=$STORK_PORT
STORK_AGENT_PORT=$STORK_AGENT_PORT
NUM_VMS=$NUM_VMS
PROJECT_ROOT=$PROJECT_ROOT
EOF
}
