server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location /apis/bss/ {
        rewrite ^/apis/bss/(.*)$ /$1 break;
        proxy_pass http://localhost:27778;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /boot/v1/ {
        proxy_pass http://localhost:27778/boot/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /hsm/ {
        proxy_pass https://localhost:27779;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_ssl_verify off;
    }

    location /cloud-init/ {
        proxy_pass http://localhost:27777/cloud-init/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /power-control/ {
        proxy_pass http://localhost:28007/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    location /hmi/v1/subscribe {
        return 200 '{"Components":[]}';
        add_header Content-Type application/json;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        autoindex on;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
