{{- if .Values.stork.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: ochami-stork-server
  labels:
    {{- include "ochami-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: stork-server
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  terminationGracePeriodSeconds: 0
  initContainers:
    - name: wait-for-postgres
      image: postgres:11.5-alpine
      command: ["sh", "-c", "until pg_isready -t 1 -h {{ .Values.stork.db.host }} -p {{ .Values.stork.db.port }}; do echo waiting for database; sleep 0.2; done;"]
  containers:
    - name: stork-server
      image: "{{ .Values.stork.server.image.repository }}:{{ .Values.stork.server.image.tag }}"
      imagePullPolicy: {{ .Values.stork.server.image.pullPolicy }}
      command: ["stork-server"]
      ports:
        - name: http
          containerPort: {{ .Values.stork.server.port }}
          protocol: TCP
      env:
        - name: STORK_DATABASE_HOST
          value: "{{ .Values.stork.db.host }}"
        - name: STORK_DATABASE_PORT
          value: {{ .Values.stork.db.port | quote }}
        - name: STORK_DATABASE_NAME
          value: "{{ .Values.stork.db.name }}"
        - name: STORK_DATABASE_USER_NAME
          value: "{{ .Values.stork.db.user }}"
        - name: STORK_DATABASE_PASSWORD
          value: {{ .Values.postgres.stork_password | quote }}
        - name: STORK_SERVER_HOST
          value: "0.0.0.0"
        - name: STORK_SERVER_PORT
          value: {{ .Values.stork.server.port | quote }}
        - name: STORK_REST_HOST
          value: "0.0.0.0"
        - name: STORK_REST_PORT
          value: {{ .Values.stork.server.port | quote }}
        - name: STORK_SERVER_ENABLE_METRICS
          value: "1"
        - name: STORK_SERVER_DISABLE_TLS
          value: "true"
        - name: STORK_REST_DISABLE_TLS
          value: "true"
      livenessProbe:
        tcpSocket:
          port: http
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
      readinessProbe:
        tcpSocket:
          port: http
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
