# -*- mode: ruby -*-
# vi: set ft=ruby :

# OpenCHAMI Multi-VM Integration Test Harness
# Usage:
#   vagrant up ubuntu --provision    # Start Ubuntu VM
#   vagrant up fedora --provision    # Start Fedora VM
#   vagrant ssh ubuntu -- sudo /home/vagrant/ochami-from-scratch/vagrant/scripts/run_tests.sh
#   vagrant destroy -f               # Clean up all VMs

VAGRANTFILE_API_VERSION = "2"

PROJECT_SYNC_EXCLUDES = [
  ".git/",
  "ochami-smd/",
  "ochami-bss/",
  "ochami-coresmd/",
  "ochami-cloud-init/",
  ".vagrant/",
  "initramfs-lts",
  "rootfs.squashfs",
  "vmlinuz-lts",
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # --- Ubuntu 24.04 VM ---
  config.vm.define "ubuntu", autostart: false do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-24.04"
    ubuntu.vm.hostname = "ochami-test-ubuntu"

    ubuntu.vm.synced_folder "..", "/home/vagrant/ochami-from-scratch",
      type: "rsync",
      rsync__exclude: PROJECT_SYNC_EXCLUDES

    ubuntu.vm.provider "libvirt" do |lv|
      lv.memory = 6144
      lv.cpus = 4
      lv.nested = true
    end

    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    ubuntu.vm.provision "shell", path: "scripts/provision.sh"
  end

  # --- Fedora 41 VM ---
  config.vm.define "fedora", autostart: false do |fedora|
    fedora.vm.box = "bento/fedora-41"
    fedora.vm.hostname = "ochami-test-fedora"

    fedora.vm.synced_folder "..", "/home/vagrant/ochami-from-scratch",
      type: "rsync",
      rsync__exclude: PROJECT_SYNC_EXCLUDES

    fedora.vm.provider "libvirt" do |lv|
      lv.memory = 6144
      lv.cpus = 4
      lv.nested = true
    end

    fedora.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    fedora.vm.provision "shell", path: "scripts/provision.sh"
  end
end
