#!/bin/bash
set -e

# scripts/deploy/docker-compose.sh — Deploy OpenCHAMI using Docker Compose

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../common.sh"

COMPOSE_DIR="$PROJECT_ROOT/ochami-docker-compose"

# --- Help ---
show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Deploy OpenCHAMI using Docker Compose with locally-built images."
    echo ""
    add_common_deploy_args_help
}

# --- Parse Arguments ---
rc=0
parse_common_deploy_args "$@" || rc=$?
if [ $rc -eq 2 ]; then
    show_help
    exit 0
elif [ $rc -ne 0 ]; then
    exit $rc
fi

validate_common_deploy_args

info "=== OpenCHAMI Docker Compose Deployment ==="

if [ "$FORCE_REBUILD" = true ]; then
    echo "Force rebuild enabled."
fi

# 0. Install Prerequisites
"$PROJECT_ROOT/scripts/install_prerequisites.sh"

# 1. Check Prerequisites
step "Checking prerequisites for docker-compose..."
require_command docker
if ! docker compose version >/dev/null 2>&1; then
    if ! command_exists docker-compose; then
        error "docker compose (plugin or standalone) is required but not installed. Aborting."
        exit 1
    fi
fi
if [ "$MODE" == "libvirt" ]; then
    require_command virt-install "virt-install is required for libvirt mode but not installed. Aborting."
fi

# Determine compose command
COMPOSE_CMD="docker compose"
if ! docker compose version >/dev/null 2>&1; then
    COMPOSE_CMD="docker-compose"
fi

# 2. Build and Load Images
step "Building and loading images..."
build_images_if_needed "docker" "docker-compose" "$FORCE_REBUILD"

# 3. Configure Network
step "Configuring PXE network (Mode: $MODE)..."

if [ "$MODE" == "hardware" ]; then
    PXE_INTERFACE=$(configure_hardware_network "$PXE_INTERFACE" "$PHY_IFACE")
    PHY_IFACE=""
fi

if [ "$MODE" == "libvirt" ]; then
    configure_libvirt_network "$PXE_INTERFACE"
else
    echo "Hardware mode selected. Skipping libvirt network creation."
fi

"$PROJECT_ROOT/scripts/setup_minikube_net.sh" "$PXE_INTERFACE" "$PXE_IP" "$PXE_CIDR" "$PHY_IFACE"

# 4. Generate configuration files
step "Generating configuration files..."
HOST_IP="$PXE_IP"
echo "Using Host IP for PXE boot: $HOST_IP"

# Export variables for envsubst
export HOST_IP PXE_INTERFACE DHCP_START DHCP_END DHCP_NETMASK PXE_CIDR
export POSTGRES_USER POSTGRES_PASSWORD
export SMD_DB_NAME SMD_DB_USER SMD_DB_PASSWORD
export BSS_DB_NAME BSS_DB_USER BSS_DB_PASSWORD
export KEA_DB_NAME KEA_DB_USER KEA_DB_PASSWORD
export HYDRA_DB_PASSWORD
export HTTP_PORT SMD_PORT BSS_PORT POSTGRES_PORT CLOUD_INIT_PORT

# Generate .env file
cat > "$COMPOSE_DIR/.env" <<EOF
# Generated by deploy/docker-compose.sh — do not edit manually
HOST_IP=$HOST_IP
PXE_INTERFACE=$PXE_INTERFACE
DHCP_START=$DHCP_START
DHCP_END=$DHCP_END
DHCP_NETMASK=$DHCP_NETMASK
PXE_CIDR=$PXE_CIDR
HTTP_PORT=$HTTP_PORT
SMD_PORT=$SMD_PORT
BSS_PORT=$BSS_PORT
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
SMD_DB_NAME=$SMD_DB_NAME
SMD_DB_USER=$SMD_DB_USER
SMD_DB_PASSWORD=$SMD_DB_PASSWORD
BSS_DB_NAME=$BSS_DB_NAME
BSS_DB_USER=$BSS_DB_USER
BSS_DB_PASSWORD=$BSS_DB_PASSWORD
KEA_DB_NAME=$KEA_DB_NAME
KEA_DB_USER=$KEA_DB_USER
KEA_DB_PASSWORD=$KEA_DB_PASSWORD
HYDRA_DB_PASSWORD=$HYDRA_DB_PASSWORD
CLOUD_INIT_PORT=$CLOUD_INIT_PORT
NUM_VMS=$NUM_VMS
PROJECT_ROOT=$PROJECT_ROOT
EOF

# Generate config files from templates
mkdir -p "$COMPOSE_DIR/configs"

if [ -f "$COMPOSE_DIR/configs/kea-dhcp4.conf.template" ]; then
    # Use explicit variable list to protect iPXE variable ${net0/mac} from substitution
    envsubst '${PXE_INTERFACE} ${KEA_DB_NAME} ${KEA_DB_USER} ${KEA_DB_PASSWORD} ${POSTGRES_PORT} ${HOST_IP} ${HTTP_PORT} ${DHCP_START} ${DHCP_END} ${PXE_CIDR}' \
        < "$COMPOSE_DIR/configs/kea-dhcp4.conf.template" > "$COMPOSE_DIR/configs/kea-dhcp4.conf"
    echo "Generated kea-dhcp4.conf"
fi

if [ -f "$COMPOSE_DIR/configs/nginx-default.conf.template" ]; then
    envsubst '${HTTP_PORT} ${BSS_PORT} ${CLOUD_INIT_PORT}' < "$COMPOSE_DIR/configs/nginx-default.conf.template" > "$COMPOSE_DIR/configs/nginx-default.conf"
    echo "Generated nginx-default.conf"
fi

if [ -f "$COMPOSE_DIR/configs/boot.ipxe.template" ]; then
    envsubst '${HOST_IP} ${HTTP_PORT}' < "$COMPOSE_DIR/configs/boot.ipxe.template" > "$COMPOSE_DIR/configs/boot.ipxe"
    echo "Generated boot.ipxe"
fi

# 5. Configure firewall
configure_firewall "$PXE_INTERFACE"

# 6. Start services
step "Starting Docker Compose services..."

COMPOSE_PROFILES=()
if [ "$NUM_VMS" -gt 0 ]; then
    COMPOSE_PROFILES=(--profile emulator)
fi

$COMPOSE_CMD -f "$COMPOSE_DIR/docker-compose.yml" --env-file "$COMPOSE_DIR/.env" "${COMPOSE_PROFILES[@]}" up -d --wait

# 7. Wait for services
step "Waiting for services to be ready..."
wait_for_url "http://localhost:${SMD_PORT}/hsm/v2/service/ready" "SMD"
wait_for_url "http://localhost:${BSS_PORT}/boot/v1/bootparameters" "BSS"
wait_for_url "http://localhost:${CLOUD_INIT_PORT}/cloud-init/version" "cloud-init"

# 8. Configure BSS
step "Configuring BSS Default Boot Parameters..."
register_bss_defaults "localhost" "$HOST_IP" "ds=nocloud-net;s=http://${HOST_IP}:${HTTP_PORT}/cloud-init/"

# 9. Create VMs
if [ "$NUM_VMS" -gt 0 ]; then
    step "Creating $NUM_VMS VMs..."
    export ORCHESTRATOR="docker-compose"
    create_and_register_vms "$NUM_VMS" "$HOST_IP"
fi

# 10. Final Instructions
info "=== Deployment Complete ==="
echo "You can now verify the services are running:"
echo "  $COMPOSE_CMD -f $COMPOSE_DIR/docker-compose.yml ps"
echo ""
echo "View logs:"
echo "  $COMPOSE_CMD -f $COMPOSE_DIR/docker-compose.yml logs -f"
echo ""
if [ "$NUM_VMS" -gt 0 ]; then
    echo "To connect to the VM console, run:"
    for i in $(seq 0 $((NUM_VMS - 1))); do
        echo "  sudo virsh start --console virtual-compute-node-$i"
    done
else
    echo "To create and boot a VM, run:"
    echo "  sudo ./scripts/create_vm.sh"
    echo "  sudo virsh start --console virtual-compute-node"
fi
