#!/bin/bash
set -e

# scripts/deploy/quadlets.sh — Deploy OpenCHAMI using individual Podman Quadlet containers

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../common.sh"

QUADLETS_DIR="$PROJECT_ROOT/ochami-quadlets"
QUADLETS_INSTALL_DIR="/etc/containers/systemd"
OPENCHAMI_CONFIG_DIR="/etc/openchami"
OPENCHAMI_CONFIGS_DIR="/etc/openchami/configs"

# --- Help ---
show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Deploy OpenCHAMI using individual Podman Quadlet containers under openchami.target."
    echo ""
    echo "Each service runs as an independent systemd unit with proper dependency ordering."
    echo "Services can be individually started/stopped/restarted."
    echo ""
    add_common_deploy_args_help
}

# --- Parse Arguments ---
rc=0
parse_common_deploy_args "$@" || rc=$?
if [ $rc -eq 2 ]; then
    show_help
    exit 0
elif [ $rc -ne 0 ]; then
    exit $rc
fi

validate_common_deploy_args

info "=== OpenCHAMI Quadlets Deployment ==="

if [ "$FORCE_REBUILD" = true ]; then
    echo "Force rebuild enabled."
fi

# 0. Install Prerequisites
"$PROJECT_ROOT/scripts/install_prerequisites.sh"

# 1. Check Prerequisites
step "Checking prerequisites for quadlets..."
require_command podman
require_command envsubst "envsubst (gettext) is required but not installed. Aborting."
if [ "$MODE" == "libvirt" ]; then
    require_command virt-install "virt-install is required for libvirt mode but not installed. Aborting."
fi

# 2. Build and Load Images
step "Building and loading images..."
build_images_if_needed "sudo podman" "quadlets" "$FORCE_REBUILD"

# 3. Configure Network
step "Configuring PXE network (Mode: $MODE)..."

if [ "$MODE" == "hardware" ]; then
    PXE_INTERFACE=$(configure_hardware_network "$PXE_INTERFACE" "$PHY_IFACE")
    PHY_IFACE=""
fi

if [ "$MODE" == "libvirt" ]; then
    configure_libvirt_network "$PXE_INTERFACE"
else
    echo "Hardware mode selected. Skipping libvirt network creation."
fi

"$PROJECT_ROOT/scripts/setup_minikube_net.sh" "$PXE_INTERFACE" "$PXE_IP" "$PXE_CIDR" "$PHY_IFACE"

# 3b. Check for DHCP port conflicts (e.g. dnsmasq from libvirt)
check_dhcp_port_conflict "$PXE_INTERFACE"

# 4. Deploy
step "Deploying OpenCHAMI (Quadlets)..."
HOST_IP="$PXE_IP"
echo "Using Host IP for PXE boot: $HOST_IP"

# Configure firewall
configure_firewall "$PXE_INTERFACE"

# 4a. Create config directory
step "Creating OpenCHAMI config directories..."
sudo mkdir -p "$OPENCHAMI_CONFIGS_DIR"

# 4b. Generate environment file
step "Generating environment file..."

# Build the POSTGRES_MULTIPLE_DATABASES string
POSTGRES_MULTIPLE_DATABASES="${SMD_DB_NAME}:${SMD_DB_USER}:${SMD_DB_PASSWORD},${BSS_DB_NAME}:${BSS_DB_USER}:${BSS_DB_PASSWORD},${KEA_DB_NAME}:${KEA_DB_USER}:${KEA_DB_PASSWORD},${PCS_DB_NAME}:${PCS_DB_USER}:${PCS_DB_PASSWORD},${STORK_DB_NAME}:${STORK_DB_USER}:${STORK_DB_PASSWORD}"

sudo tee "$OPENCHAMI_CONFIG_DIR/openchami.env" > /dev/null <<EOF
# OpenCHAMI Environment Configuration (auto-generated by deploy script)

# Network
HOST_IP=${HOST_IP}
PXE_INTERFACE=${PXE_INTERFACE}
PXE_CIDR=${PXE_CIDR}
DHCP_START=${DHCP_START}
DHCP_END=${DHCP_END}
DHCP_NETMASK=${DHCP_NETMASK}

# Service ports
HTTP_PORT=${HTTP_PORT}
SMD_PORT=${SMD_PORT}
BSS_PORT=${BSS_PORT}
POSTGRES_PORT=${POSTGRES_PORT}
CLOUD_INIT_PORT=${CLOUD_INIT_PORT}
PCS_PORT=${PCS_PORT}
STORK_PORT=${STORK_PORT}
STORK_AGENT_PORT=${STORK_AGENT_PORT}

# PostgreSQL
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}

# SMD Database
SMD_DBPORT=${POSTGRES_PORT}
SMD_DBNAME=${SMD_DB_NAME}
SMD_DBUSER=${SMD_DB_USER}
SMD_DBPASS=${SMD_DB_PASSWORD}
SMD_DBOPTS=sslmode=disable

# BSS Database
BSS_DBPORT=${POSTGRES_PORT}
BSS_DBNAME=${BSS_DB_NAME}
BSS_DBUSER=${BSS_DB_USER}
BSS_DBPASS=${BSS_DB_PASSWORD}
BSS_DBOPTS=sslmode=disable
HSM_URL=http://localhost:${SMD_PORT}
BSS_IPXE_SERVER=${HOST_IP}
BSS_ADVERTISE_ADDRESS=${HOST_IP}
NFD_URL=http://${HOST_IP}:${HTTP_PORT}/hmi/v1/subscribe
SMS_SERVER=http://localhost:${SMD_PORT}

# Kea Database
KEA_DB_NAME=${KEA_DB_NAME}
KEA_DB_USER=${KEA_DB_USER}
KEA_DB_PASSWORD=${KEA_DB_PASSWORD}

# Stork
STORK_DB_NAME=${STORK_DB_NAME}
STORK_DB_USER=${STORK_DB_USER}
STORK_DB_PASSWORD=${STORK_DB_PASSWORD}
STORK_AGENT_SERVER_URL=http://localhost:${STORK_PORT}
STORK_AGENT_HOST=${HOST_IP}
STORK_AGENT_PORT=${STORK_AGENT_PORT}

# Kea sidecar
DB_NAME=${KEA_DB_NAME}
DB_USER=${KEA_DB_USER}
DB_PASS=${KEA_DB_PASSWORD}
DB_PORT=${POSTGRES_PORT}
EOF

# 4c. Process config templates with envsubst
step "Processing config templates..."

# Export all variables needed by templates
export HOST_IP PXE_INTERFACE PXE_CIDR DHCP_START DHCP_END DHCP_NETMASK
export HTTP_PORT SMD_PORT BSS_PORT POSTGRES_PORT CLOUD_INIT_PORT PCS_PORT STORK_PORT STORK_AGENT_PORT
export KEA_DB_NAME KEA_DB_USER KEA_DB_PASSWORD
export STORK_DB_NAME STORK_DB_USER STORK_DB_PASSWORD

# Template variables to substitute (exclude nginx $host, $remote_addr, etc.)
ENVSUBST_VARS='${HOST_IP} ${PXE_INTERFACE} ${PXE_CIDR} ${DHCP_START} ${DHCP_END} ${DHCP_NETMASK} ${HTTP_PORT} ${SMD_PORT} ${BSS_PORT} ${POSTGRES_PORT} ${CLOUD_INIT_PORT} ${PCS_PORT} ${STORK_PORT} ${STORK_AGENT_PORT} ${KEA_DB_NAME} ${KEA_DB_USER} ${KEA_DB_PASSWORD} ${STORK_DB_NAME} ${STORK_DB_USER} ${STORK_DB_PASSWORD}'

# Process .template files
for tmpl in "$QUADLETS_DIR/configs/"*.template; do
    [ -f "$tmpl" ] || continue
    base=$(basename "$tmpl" .template)
    echo "  Processing $base..."
    envsubst "$ENVSUBST_VARS" < "$tmpl" | sudo tee "$OPENCHAMI_CONFIGS_DIR/$base" > /dev/null
done

# Copy static config files
for static_file in "$QUADLETS_DIR/configs/"*.sh "$QUADLETS_DIR/configs/"*.py "$QUADLETS_DIR/configs/"*.conf "$QUADLETS_DIR/configs/"*.html "$QUADLETS_DIR/configs/user-data" "$QUADLETS_DIR/configs/meta-data"; do
    [ -f "$static_file" ] || continue
    base=$(basename "$static_file")
    # Skip .template files (already processed above)
    if [[ "$base" == *.template ]]; then
        continue
    fi
    echo "  Copying $base..."
    sudo cp "$static_file" "$OPENCHAMI_CONFIGS_DIR/$base"
done

# Ensure postgres init script is executable
sudo chmod +x "$OPENCHAMI_CONFIGS_DIR/postgres-init-db.sh"

# 4d. Install quadlet files
step "Installing Quadlet files to $QUADLETS_INSTALL_DIR..."
sudo mkdir -p "$QUADLETS_INSTALL_DIR"

# Process .container files through envsubst (for Exec lines that need substituted values)
# then install to quadlet directory
for unit_file in "$QUADLETS_DIR/containers/"*.container; do
    [ -f "$unit_file" ] || continue
    base=$(basename "$unit_file")
    echo "  Installing $base..."
    envsubst "$ENVSUBST_VARS" < "$unit_file" | sudo tee "$QUADLETS_INSTALL_DIR/$base" > /dev/null
done

# Install .target files to systemd directory (targets are plain systemd units, not quadlets)
for unit_file in "$QUADLETS_DIR/containers/"*.target; do
    [ -f "$unit_file" ] || continue
    base=$(basename "$unit_file")
    echo "  Installing $base to /etc/systemd/system/..."
    sudo cp "$unit_file" "/etc/systemd/system/$base"
done

# 4e. Generate redfish emulator containers (if VMs requested)
if [ "$NUM_VMS" -gt 0 ]; then
    step "Generating $NUM_VMS redfish emulator quadlet files..."
    for i in $(seq 0 $((NUM_VMS - 1))); do
        EMULATOR_FILE="$QUADLETS_INSTALL_DIR/redfish-emulator-${i}.container"
        echo "  Generating redfish-emulator-${i}.container..."
        sudo tee "$EMULATOR_FILE" > /dev/null <<EMULATOR_EOF
[Unit]
Description=OpenCHAMI Redfish Emulator (VM $i)

[Container]
Image=localhost/redfish-emulator:latest
Network=host
Environment=VM_INDEX=$i
Exec=python -u -c "import os; idx=os.environ.get('VM_INDEX','0'); script=open('/emulator.py').read(); script=script.replace('INDEX = int(HOSTNAME.split(\"-\")[-1])', f'INDEX = {idx}'); exec(script)"
Volume=/var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock

[Service]
Restart=on-failure
TimeoutStartSec=60

[Install]
WantedBy=openchami.target
EMULATOR_EOF
    done
fi

# 4f. Start services
step "Reloading systemd and starting OpenCHAMI services..."
sudo systemctl daemon-reload
sudo systemctl start openchami.target

# Wait for services
echo "Waiting for services to start..."
wait_for_url "http://localhost:${SMD_PORT}/hsm/v2/service/ready" "SMD"
wait_for_url "http://localhost:${BSS_PORT}/boot/v1/bootparameters" "BSS"
wait_for_url "http://localhost:${CLOUD_INIT_PORT}/cloud-init/version" "cloud-init"
wait_for_url "http://localhost:${PCS_PORT}/liveness" "PCS (Power Control)"
wait_for_url "http://localhost:${STORK_PORT}/api/version" "Stork (Kea DHCP Monitor)"

# 5. Configure BSS
step "Configuring BSS Default Boot Parameters..."
register_bss_defaults "$HOST_IP" "$HOST_IP" "ds=nocloud-net;s=http://${HOST_IP}:${HTTP_PORT}/cloud-init/"

# 6. Create VMs
if [ "$NUM_VMS" -gt 0 ]; then
    step "Creating $NUM_VMS VMs..."
    create_and_register_vms "$NUM_VMS" "$HOST_IP"
fi

# 7. Final Instructions
info "=== Deployment Complete ==="
echo "  Stork DHCP Monitor: http://localhost:${STORK_PORT}/ (login: admin/admin)"
echo ""
echo "You can now verify the services are running:"
echo "  systemctl list-dependencies openchami.target"
echo "  sudo podman ps"
echo ""
echo "Individual service management:"
echo "  sudo systemctl status smd"
echo "  sudo systemctl restart bss"
echo "  sudo journalctl -u smd -f"
echo ""
if [ "$NUM_VMS" -gt 0 ]; then
    echo "To connect to the VM console, run:"
    for i in $(seq 0 $((NUM_VMS - 1))); do
        echo "  sudo virsh start --console virtual-compute-node-$i"
    done
else
    echo "To create and boot a VM, run:"
    echo "  sudo ./scripts/create_vm.sh"
    echo "  sudo virsh start --console virtual-compute-node"
fi
