apiVersion: v1
kind: Service
metadata:
  name: {{ include "ochami-helm.fullname" . }}-coredhcp
  labels:
    {{- include "ochami-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: coredhcp
spec:
  type: {{ .Values.service.coredhcp.type }}
  ports:
    - port: {{ .Values.service.coredhcp.port }}
      protocol: UDP
      name: dhcp
  selector:
    {{- include "ochami-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coredhcp
