{{- if .Values.httpServer.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: ochami-http-server
  labels:
    {{- include "ochami-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: http-server
spec:
  hostNetwork: {{ .Values.httpServer.hostNetwork }}
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: http-server
      image: "{{ .Values.httpServer.image.repository }}:{{ .Values.httpServer.image.tag }}"
      imagePullPolicy: {{ .Values.httpServer.image.pullPolicy }}
      ports:
        - containerPort: {{ .Values.httpServer.port }}
      volumeMounts:
        - name: http-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: http-content
          mountPath: /usr/share/nginx/html/boot.ipxe
          subPath: boot.ipxe
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
  volumes:
    - name: http-content
      configMap:
        name: {{ include "ochami-helm.fullname" . }}-http-server-content
    - name: nginx-config
      configMap:
        name: {{ include "ochami-helm.fullname" . }}-http-server-config
{{- end }}
