apiVersion: v1
kind: Pod
metadata:
  name: ochami-kea
  labels:
    {{- include "ochami-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kea
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  initContainers:
    - name: wait-for-interface
      image: alpine:3.18
      command: ["sh", "-c", "until ip link show {{ .Values.pxeInterface }} | grep -q 'state UP'; do echo waiting for {{ .Values.pxeInterface }}; sleep 0.2; done;"]
    - name: wait-for-postgres
      image: postgres:11.5-alpine
      command: ["sh", "-c", "until pg_isready -t 1 -h ochami-postgres -p 5432; do echo waiting for database; sleep 0.2; done;"]
    - name: init-kea-db
      image: "{{ .Values.kea.adminImage.repository }}:{{ .Values.kea.adminImage.tag }}"
      env:
        - name: KEA_DB_PASSWORD
          value: "{{ .Values.postgres.kea_password }}"
      command: ["/bin/bash", "-c", "kea-admin db-init pgsql -u {{ .Values.kea.db.user }} -p $KEA_DB_PASSWORD -n {{ .Values.kea.db.name }} -h {{ .Values.kea.db.host }} || echo 'Database already initialized'"]
  containers:
    - name: kea-dhcp4
      image: "{{ .Values.kea.image.repository }}:{{ .Values.kea.image.tag }}"
      imagePullPolicy: "{{ .Values.kea.image.pullPolicy }}"
      args: ["-c", "/etc/kea/kea-dhcp4.conf"]
      volumeMounts:
        - name: kea-config
          mountPath: /etc/kea/kea-dhcp4.conf
          subPath: kea-dhcp4.conf
    - name: sidecar
      image: "{{ .Values.kea.sidecar.image.repository }}:{{ .Values.kea.sidecar.image.tag }}"
      imagePullPolicy: "{{ .Values.kea.sidecar.image.pullPolicy }}"
      command: ["/bin/sh", "-c"]
      args: ["pip install psycopg2-binary requests && python /scripts/smd_sync.py"]
      env:
        - name: SMD_URL
          value: "http://ochami-smd.ochami.svc.cluster.local:27779"
        - name: DB_NAME
          value: "{{ .Values.kea.db.name }}"
        - name: DB_USER
          value: "{{ .Values.kea.db.user }}"
        - name: DB_PASS
          value: "{{ .Values.postgres.kea_password }}"
        - name: DB_HOST
          value: "{{ .Values.kea.db.host }}"
        - name: DB_PORT
          value: {{ .Values.kea.db.port | quote }}
      volumeMounts:
        - name: kea-config
          mountPath: /scripts/smd_sync.py
          subPath: smd_sync.py
  volumes:
    - name: kea-config
      configMap:
        name: {{ include "ochami-helm.fullname" . }}-kea-config