apiVersion: v1
kind: Pod
metadata:
  name: ochami-kea
  labels:
    {{- include "ochami-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kea
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: kea
      image: "{{ .Values.kea.image.repository }}:{{ .Values.kea.image.tag }}"
      imagePullPolicy: {{ .Values.kea.image.pullPolicy }}
      securityContext:
        capabilities:
          add:
            - "NET_ADMIN"
      volumeMounts:
        - name: kea-config
          mountPath: /etc/kea/kea-dhcp4.conf
          subPath: kea-dhcp4.conf
  volumes:
    - name: kea-config
      configMap:
        name: {{ include "ochami-helm.fullname" . }}-kea-config
