apiVersion: v1
kind: Service
metadata:
  name: {{ include "ochami-helm.fullname" . }}-kea
  labels:
    {{- include "ochami-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: kea
spec:
  type: ClusterIP
  ports:
    - port: 67
      protocol: UDP
      name: dhcp
  selector:
    {{- include "ochami-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kea
