apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ochami-helm.fullname" . }}-kea-config
  labels:
    {{- include "ochami-helm.labels" . | nindent 4 }}
data:
  kea-dhcp4.conf: |
    {
      "Dhcp4": {
        "interfaces-config": {
          "interfaces": ["{{ .Values.pxeInterface }}"]
        },
        "control-socket": {
            "socket-type": "unix",
            "socket-name": "/kea/sockets/kea4-ctrl-socket"
        },
        "hooks-libraries": [
          {
            "library": "/usr/local/lib/kea/hooks/libdhcp_pgsql.so"
          }
        ],
        "lease-database": {
          "type": "postgresql",
          "name": "{{ .Values.kea.db.name }}",
          "user": "{{ .Values.kea.db.user }}",
          "password": "{{ .Values.postgres.kea_password }}",
          "host": "{{ .Values.kea.db.host }}",
          "port": {{ .Values.kea.db.port }}
        },
        "hosts-database": {
          "type": "postgresql",
          "name": "{{ .Values.kea.db.name }}",
          "user": "{{ .Values.kea.db.user }}",
          "password": "{{ .Values.postgres.kea_password }}",
          "host": "{{ .Values.kea.db.host }}",
          "port": {{ .Values.kea.db.port }}
        },
        "valid-lifetime": 300,
        "renew-timer": 150,
        "rebind-timer": 225,

        # PXE Chainloading Classes
        "client-classes": [
          {
            "name": "iPXE",
            "test": "substring(option[77].hex,0,4) == 'iPXE'",
            "boot-file-name": "{{ .Values.bootScriptUrl | default (printf "http://%s:%v/boot.ipxe" .Values.externalIp (int (.Values.httpServer.service.nodePort | default 30080))) }}"
          },
          {
            "name": "BIOS",
            "test": "option[93].hex == 0x0000",
            "boot-file-name": "undionly.kpxe"
          },
          {
            "name": "UEFI-64",
            "test": "option[93].hex == 0x0007 or option[93].hex == 0x0009",
            "boot-file-name": "ipxe.efi"
          }
        ],

        "subnet4": [
          {
            "id": 1,
            "subnet": "{{ .Values.externalIp }}/{{ .Values.dhcpCidr | default "24" }}",
            "pools": [
              {
                "pool": "{{ .Values.dhcpStart }} - {{ .Values.dhcpEnd }}"
              }
            ],
            "option-data": [
              {
                "name": "routers",
                "data": "{{ .Values.externalIp }}"
              },
              {
                "name": "domain-name-servers",
                "data": "8.8.8.8"
              },
              {
                 "name": "tftp-server-name",
                 "data": "{{ .Values.tftpServerIp | default .Values.externalIp }}"
              }
            ]
          }
        ]
      }
    }

  kea-ctrl-agent.conf: |
    {
      "Control-agent": {
        "http-host": "127.0.0.1",
        "http-port": 8000,
        "control-sockets": {
          "dhcp4": {
            "socket-type": "unix",
            "socket-name": "/kea/sockets/kea4-ctrl-socket"
          }
        }
      }
    }
