apiVersion: v1
kind: Pod
metadata:
  name: ochami-kea
  labels:
    {{- include "ochami-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kea
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  shareProcessNamespace: true
  initContainers:
    - name: wait-for-interface
      image: alpine:3.18
      command: ["sh", "-c", "until ip link show {{ .Values.pxeInterface }} | grep -q 'state UP'; do echo waiting for {{ .Values.pxeInterface }}; sleep 0.2; done;"]
    - name: wait-for-postgres
      image: postgres:11.5-alpine
      command: ["sh", "-c", "until pg_isready -t 1 -h ochami-postgres -p 5432; do echo waiting for database; sleep 0.2; done;"]
    - name: init-kea-db
      image: "{{ .Values.kea.adminImage.repository }}:{{ .Values.kea.adminImage.tag }}"
      env:
        - name: KEA_DB_PASSWORD
          value: "{{ .Values.postgres.kea_password }}"
      command: ["/bin/bash", "-c", "kea-admin db-init pgsql -u {{ .Values.kea.db.user }} -p $KEA_DB_PASSWORD -n {{ .Values.kea.db.name }} -h {{ .Values.kea.db.host }} || echo 'Database already initialized'"]
    - name: fix-socket-dir
      image: alpine:3.18
      command: ["sh", "-c", "chmod 750 /kea/sockets"]
      volumeMounts:
        - name: kea-run-dir
          mountPath: /kea/sockets
  containers:
    - name: kea-dhcp4
      image: "{{ .Values.kea.image.repository }}:{{ .Values.kea.image.tag }}"
      imagePullPolicy: "{{ .Values.kea.image.pullPolicy }}"
      securityContext:
        capabilities:
          add:
            - NET_RAW
            - NET_ADMIN
      args: ["-c", "/etc/kea/kea-dhcp4.conf"]
      volumeMounts:
        - name: kea-config
          mountPath: /etc/kea/kea-dhcp4.conf
          subPath: kea-dhcp4.conf
        - name: kea-run-dir
          mountPath: /kea/sockets
    - name: sidecar
      image: "{{ .Values.kea.sidecar.image.repository }}:{{ .Values.kea.sidecar.image.tag }}"
      imagePullPolicy: "{{ .Values.kea.sidecar.image.pullPolicy }}"
      command: ["/bin/sh", "-c"]
      args: ["pip install psycopg2-binary requests && python /scripts/smd_sync.py"]
      env:
        - name: SMD_URL
          value: "http://ochami-smd.ochami.svc.cluster.local:27779"
        - name: DB_NAME
          value: "{{ .Values.kea.db.name }}"
        - name: DB_USER
          value: "{{ .Values.kea.db.user }}"
        - name: DB_PASS
          value: "{{ .Values.postgres.kea_password }}"
        - name: DB_HOST
          value: "{{ .Values.kea.db.host }}"
        - name: DB_PORT
          value: {{ .Values.kea.db.port | quote }}
      volumeMounts:
        - name: kea-config
          mountPath: /scripts/smd_sync.py
          subPath: smd_sync.py
    {{- if .Values.stork.enabled }}
    - name: kea-ctrl-agent
      image: "{{ .Values.kea.ctrlAgent.image.repository }}:{{ .Values.kea.ctrlAgent.image.tag }}"
      imagePullPolicy: {{ .Values.kea.ctrlAgent.image.pullPolicy }}
      args: ["-c", "/etc/kea/kea-ctrl-agent.conf"]
      volumeMounts:
        - name: kea-config
          mountPath: /etc/kea/kea-ctrl-agent.conf
          subPath: kea-ctrl-agent.conf
        - name: kea-run-dir
          mountPath: /kea/sockets
    - name: stork-agent
      image: "{{ .Values.stork.agent.image.repository }}:{{ .Values.stork.agent.image.tag }}"
      imagePullPolicy: {{ .Values.stork.agent.image.pullPolicy }}
      securityContext:
        capabilities:
          add:
            - SYS_PTRACE
      env:
        - name: STORK_AGENT_SERVER_URL
          value: "http://ochami-stork-server.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.stork.server.port }}"
        - name: STORK_AGENT_HOST
          value: "{{ .Values.externalIp }}"
        - name: STORK_AGENT_PORT
          value: "{{ .Values.stork.agent.port }}"
      volumeMounts:
        - name: kea-config
          mountPath: /etc/kea/kea-dhcp4.conf
          subPath: kea-dhcp4.conf
        - name: kea-config
          mountPath: /etc/kea/kea-ctrl-agent.conf
          subPath: kea-ctrl-agent.conf
        - name: kea-run-dir
          mountPath: /kea/sockets
    {{- end }}
  volumes:
    - name: kea-config
      configMap:
        name: {{ include "ochami-helm.fullname" . }}-kea-config
    - name: kea-run-dir
      emptyDir: {}