apiVersion: v1
kind: Pod
metadata:
  name: ochami-postgres
  labels:
    {{- include "ochami-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  containers:
    - name: postgres
      image: "{{ .Values.image.postgres.repository }}:{{ .Values.image.postgres.tag }}"
      imagePullPolicy: {{ .Values.image.postgres.pullPolicy }}
      ports:
        - name: postgres
          containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password | quote }}
        - name: POSTGRES_MULTIPLE_DATABASES
          value: "hmsds:smd-user:{{ .Values.postgres.smd_password }},bssdb:bss-user:{{ .Values.postgres.bss_password }},hydradb:hydra-user:{{ .Values.postgres.hydra_password }}"
      readinessProbe:
        exec:
          command:
            - "pg_isready"
            - "-U"
            - "{{ .Values.postgres.user }}"
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      volumeMounts:
        - name: postgres-init-scripts
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: postgres-init-scripts
      configMap:
        name: {{ include "ochami-helm.fullname" . }}-postgres-init
        defaultMode: 0755
