affinity: {}
bss:
  advertise_address: localhost
  bootscript:
    notify_url: ""
  chain:
    proto: http
  db:
    host: ochami-postgres
    name: bssdb
    opts: sslmode=disable
    port: 15432
    user: bss-user
  image:
    pullPolicy: IfNotPresent
    repository: localhost/bss
    tag: v1.32.2
  ipxe:
    server: 192.168.100.1
  jwks:
    url: ""
  nfdUrl: ""
bssInit:
  image:
    pullPolicy: IfNotPresent
    repository: localhost/bss
    tag: v1.32.2
cloudInit:
  clusterName: ochami
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: localhost/cloud-init
    tag: v1.4.0
  port: 27777
emulator:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: localhost/redfish-emulator
    tag: latest
  libvirtSocket:
    enabled: true
    hostPath: /var/run/libvirt/libvirt-sock
    mountPath: /var/run/libvirt/libvirt-sock
  replicas: 0
  vmPrefix: virtual-compute-node-
externalIp: 192.168.100.1
fullnameOverride: ochami
httpServer:
  enabled: false
  hostNetwork: false
  image:
    pullPolicy: IfNotPresent
    repository: localhost/http-server
    tag: latest
  port: 80
  service:
    nodePort: 30080
    port: 80
    type: NodePort
image:
  postgres:
    pullPolicy: IfNotPresent
    repository: docker.io/postgres
    tag: 11.5-alpine
  smd:
    pullPolicy: IfNotPresent
    repository: localhost/smd
    tag: v2.19.2
imagePullSecrets: []
kea:
  adminImage:
    pullPolicy: IfNotPresent
    repository: localhost/kea
    tag: 3.0.2
  controlPort: 8000
  db:
    host: ochami-postgres
    name: kea
    password: ""
    port: 15432
    user: kea-user
  hookLibraryDir: /usr/lib/x86_64-linux-gnu/kea/hooks
  image:
    pullPolicy: IfNotPresent
    repository: localhost/kea
    tag: 3.0.2
  sync:
    image:
      pullPolicy: IfNotPresent
      repository: localhost/kea-sync
      tag: main
nameOverride: ""
nodeSelector: {}
pcs:
  db:
    host: ochami-postgres
    name: pcsdb
    opts: sslmode=disable
    port: 15432
    user: pcs-user
  image:
    pullPolicy: IfNotPresent
    repository: localhost/pcs
    tag: main
pcsInit:
  image:
    pullPolicy: IfNotPresent
    repository: localhost/pcs
    tag: main
podAnnotations: {}
podSecurityContext: {}
postgres:
  bss_password: ""
  hydra_password: ""
  kea_password: ""
  password: ""
  pcs_password: ""
  smd_password: ""
  stork_password: ""
  user: ochami
pxeInterface: virbr-ochami
replicaCount: 1
resources: {}
securityContext: {}
service:
  bss:
    port: 27778
    type: ClusterIP
  cloudInit:
    port: 27777
    type: ClusterIP
  kea:
    port: 67
    type: ClusterIP
  pcs:
    port: 28007
    type: ClusterIP
  postgres:
    port: 15432
    type: ClusterIP
  smd:
    port: 27779
    type: ClusterIP
  stork:
    port: 28010
    type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ""
smd:
  db:
    host: ochami-postgres
    name: hmsds
    opts: sslmode=disable
    port: 15432
    user: smd-user
  jwks:
    url: ""
smdInit:
  image:
    pullPolicy: IfNotPresent
    repository: localhost/smd
    tag: v2.19.2
stork:
  agent:
    image:
      pullPolicy: IfNotPresent
      repository: localhost/stork-agent
      tag: latest
    port: 28011
  db:
    host: ochami-postgres
    name: stork
    port: 15432
    user: stork-user
  enabled: true
  server:
    image:
      pullPolicy: IfNotPresent
      repository: docker.io/signalorange/stork
      tag: ubuntu24.04-1.19.0
    port: 28010
terminationGracePeriodSeconds: 30
tftp:
  enabled: true
  hostNetwork: true
  image:
    pullPolicy: IfNotPresent
    repository: localhost/tftp
    tag: latest
  port: 69
tolerations: []
