from __future__ import annotations

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from pathlib import Path

from ochami.config import DeployConfig
from ochami.console import Console, NullConsole
from ochami.defaults import DEFAULT_PORTS
from ochami.state import AppliedState, config_hash, load_state, needs_apply, save_state

LOCALHOST_HEALTH_CHECKS: list[tuple[str, str]] = [
    ("SMD", f"http://localhost:{DEFAULT_PORTS['SMD_PORT']}/hsm/v2/service/ready"),
    ("BSS", f"http://localhost:{DEFAULT_PORTS['BSS_PORT']}/boot/v1/bootparameters"),
    ("cloud-init", f"http://localhost:{DEFAULT_PORTS['CLOUD_INIT_PORT']}/version"),
    ("PCS", f"http://localhost:{DEFAULT_PORTS['PCS_PORT']}/liveness"),
    ("Stork", f"http://localhost:{DEFAULT_PORTS['STORK_PORT']}/api/version"),
]


class BaseDeployer(ABC):
    # Subclasses must set ``project_root: Path`` before calling
    # ``write_mcp_defaults``.

    console: Console

    def run(
        self,
        config: DeployConfig,
        dry_run: bool = False,
        console: Console | None = None,
    ) -> None:
        self.console = console or NullConsole()
        self.console.header(f"Deploying OpenCHAMI ({self._method_label()})")

        with self.console.phase("Validating configuration..."):
            self.validate(config)

        with self.console.phase("Configuring network...") as ctx:
            host_ip = self.configure_network(config, dry_run=dry_run)
            ctx.set_detail(host_ip)

        self.deploy(config, host_ip=host_ip, dry_run=dry_run)
        self.post_deploy(config, host_ip=host_ip, dry_run=dry_run)

        self.console.footer(
            "Deploy complete.",
            details={"MCP": f"http://{host_ip}:{self._mcp_port()}"},
        )

    def apply(
        self,
        config: DeployConfig,
        *,
        state_path: Path,
        force: bool = False,
        dry_run: bool = False,
        console: Console | None = None,
    ) -> None:
        self.console = console or NullConsole()

        with self.console.phase("Validating configuration..."):
            self.validate(config)

        current = config_hash(config)
        saved = load_state(state_path)
        if not force and not needs_apply(current, saved):
            with self.console.phase("Config unchanged, running health check..."):
                self.ensure_healthy(config, dry_run=dry_run)
            self.console.footer("Already up to date.")
            return

        self.console.header(f"Deploying OpenCHAMI ({self._method_label()})")

        with self.console.phase("Configuring network...") as ctx:
            host_ip = self.configure_network(config, dry_run=dry_run)
            ctx.set_detail(host_ip)

        self.deploy(config, host_ip=host_ip, dry_run=dry_run)
        self.post_deploy(config, host_ip=host_ip, dry_run=dry_run)
        if not dry_run:
            save_state(
                state_path,
                AppliedState(
                    config_hash=current,
                    method=config.method.value,
                    timestamp=datetime.now(timezone.utc).isoformat(),
                ),
            )
        self.console.footer(
            "Deploy complete.",
            details={"MCP": f"http://{host_ip}:{self._mcp_port()}"},
        )

    def ensure_healthy(self, config: DeployConfig, dry_run: bool = False) -> None:
        """Lightweight health check — overridden by subclasses."""

    def validate(self, config: DeployConfig) -> None:
        config.validate()

    def _method_label(self) -> str:
        """Human-readable method name — overridden by subclasses."""
        return "unknown"

    def _mcp_port(self) -> int | str:
        """Port shown in the footer MCP URL — overridden by minikube."""
        return DEFAULT_PORTS["HTTP_PORT"]

    def write_mcp_defaults(
        self,
        *,
        host_ip: str,
        http_port: int | str,
        method_label: str,
        dry_run: bool,
    ) -> None:
        """Write ``.openchami-mcp.env`` with deployment-specific defaults."""
        if dry_run:
            return
        path: Path = self.project_root / ".openchami-mcp.env"  # type: ignore[attr-defined]
        path.write_text(
            (
                f"# Generated by ochamifs deploy --method {method_label}\n"
                f"# OpenCHAMI MCP defaults ({method_label} host reverse proxy)\n"
                f"OPENCHAMI_BASE_URL=http://{host_ip}:{http_port}\n"
                "OPENCHAMI_MCP_MODE=read-only\n"
                "# Set to true only when you explicitly want mutating operations.\n"
                "OPENCHAMI_MCP_ENABLE_WRITES=false\n"
            ),
            encoding="utf-8",
        )

    @abstractmethod
    def configure_network(self, config: DeployConfig, dry_run: bool) -> str:
        raise NotImplementedError

    @abstractmethod
    def deploy(self, config: DeployConfig, host_ip: str, dry_run: bool) -> None:
        raise NotImplementedError

    @abstractmethod
    def post_deploy(self, config: DeployConfig, host_ip: str, dry_run: bool) -> None:
        raise NotImplementedError
